/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface XephAutocomplete {
    'placeholder': string;
    'validarr': string[];
  }
  interface XephAutocompleteAttributes extends StencilHTMLAttributes {
    'placeholder'?: string;
    'validarr'?: string[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'XephAutocomplete': Components.XephAutocomplete;
  }

  interface StencilIntrinsicElements {
    'xeph-autocomplete': Components.XephAutocompleteAttributes;
  }


  interface HTMLXephAutocompleteElement extends Components.XephAutocomplete, HTMLStencilElement {}
  var HTMLXephAutocompleteElement: {
    prototype: HTMLXephAutocompleteElement;
    new (): HTMLXephAutocompleteElement;
  };

  interface HTMLElementTagNameMap {
    'xeph-autocomplete': HTMLXephAutocompleteElement
  }

  interface ElementTagNameMap {
    'xeph-autocomplete': HTMLXephAutocompleteElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
